Quiz/Areas/Admin/Controllers/AlternativaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Quiz._Repositorys.core;
using Quiz.Areas.Admin.Models;


namespace Quiz.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AlternativaController : Controller
    {
        IAlternativaRepository AlternativaRep;
        IQuestaoRepository Questaorep;
        public AlternativaController(IAlternativaRepository alternativaRep, IQuestaoRepository questaoRep)
        {
            AlternativaRep = alternativaRep;
            Questaorep = questaoRep;
        }
        // GET: Alternativa
        public IActionResult Index()
        {
            var item = AlternativaRep.Get(); //trazer tudo no index: get vazio
            return View(item);
        }

        // GET: Alternativa/Details/5
        public IActionResult Details(int IDAlternativa)
        {
            return View(AlternativaRep.GetbyID(IDAlternativa));
        }

        // GET: Alternativa/Create
        public IActionResult Create(int IdQuestao)
        {
            ViewBag.Questao =new SelectList(Questaorep.Get().ToList(), "IDQuestao", "Enunciado");
            return View(new Alternativa { IDQuestao = IdQuestao } );
        }

        // POST: Alternativa/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Alternativa item, int IDQuestao)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Questao = Questaorep.GetbyID(IDQuestao);
                item.IDQuestao = IDQuestao;
                AlternativaRep.Include(item);
                return RedirectToAction("Index");
            }
            else
            {
                string errors = string.Empty;
                foreach (var erro in ModelState)
                {
                    errors += $"{erro}\n";
                }
                return View(errors);
            }
        }

        // GET: Alternativa/Edit/5
        public IActionResult Edit(int IDAlternativa)
        {
            return View(AlternativaRep.GetbyID(IDAlternativa));
        }

        // POST: Alternativa/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Alternativa item)
        {
            if (ModelState.IsValid)
            {
                AlternativaRep.Update(item);
                return RedirectToAction("Index");
            }
            else
            {
                string errors = string.Empty;
                foreach (var erro in ModelState)
                {
                    errors += $"{erro}\n";
                }
                return View(errors);
            }
        }

        // GET: Alternativa/Delete/5
        public IActionResult Delete(int IDAlternativa)
        {
            return View(AlternativaRep.GetbyID(IDAlternativa));
        }

        // POST: Alternativa/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletar(int IDAlternativa)
        {
            if (ModelState.IsValid)
            {
                AlternativaRep.Delete(IDAlternativa);
                return RedirectToAction("Index");
            }
            else
            {
                string errors = string.Empty;
                foreach (var erro in ModelState)
                {
                    errors += $"{erro}\n";
                }
                return View(errors);
            }
        }
    }
}

Quiz/Areas/Admin/Controllers/QuestaoController.cs
using Microsoft.AspNetCore.Mvc;
using Quiz._Repositorys.core;
using Quiz.Areas.Admin.Models;

namespace Quiz.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class QuestaoController : Controller
    {
        public IQuestaoRepository QuestaoRep;
        public QuestaoController(IQuestaoRepository questaoRep)
        {
            QuestaoRep = questaoRep;
        }
        // GET: Questao
        public IActionResult Index()
        {
            var item = QuestaoRep.Get(); //trazer tudo no index: get vazio
            return View(item);
        }

        // GET: Questao/Details/5
        public IActionResult Details(int IDQuestao)
        {
            var a = QuestaoRep.GetbyID(IDQuestao);
            return View(a);
        }

        // GET: Questao/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Questao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Questao item)
        {
            if (ModelState.IsValid)
            {
                QuestaoRep.Include(item);
                return RedirectToAction("Index");
            }
            else
            {
                string errors = string.Empty;
                foreach (var erro in ModelState)
                {
                    errors += $"{erro}\n";
                }
                return View(errors);
            }
        }

        // GET: Questao/Edit/5
        public IActionResult Edit(int IDQuestao)
        {
            return View(QuestaoRep.GetbyID(IDQuestao));
        }

        // POST: Questao/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Questao item)
        {
            if (ModelState.IsValid)
            {
                QuestaoRep.Update(item);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Questao/Delete/5
        public IActionResult Delete(int IDQuestao)
        {
            return View(QuestaoRep.GetbyID(IDQuestao));
        }

        // POST: Questao/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletar(int IDQuestao)
        {
            if (ModelState.IsValid)
            {
                QuestaoRep.Delete(IDQuestao); //fazer "hidden" na view do delete (pq é update)
                return RedirectToAction("Index");
            }
            else
            {
                string errors = string.Empty;
                foreach (var erro in ModelState)
                {
                    errors += $"{erro}\n";
                }
                return View(errors);
            }
        }
    }
}

Quiz/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - Admin</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="~/images/Favicon.png" />
    <!-- Bootstrap 3.3.7 -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/lib/bootstrap/dist/css/font-awesome.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/css/AdminLTE.css" rel="stylesheet" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/css/skins/skin-purple.css" rel="stylesheet" />
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-purple sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <span class="logo-lg"><b>Quiz</b></span>
                <span class="logo-mini"><b>Quiz</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">NAVIGATION MENU</li>

                    <li>
                        <a asp-controller="Questao" asp-action="Index" asp-area="Admin">
                            <i class="fa fa-file-text-o"></i>
                            <span>Questions</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Alternativa" asp-action="Index" asp-area="Admin">
                            <i class="fa fa-check-square-o"></i>
                            <span>Alternatives</span>
                        </a>
                    </li>
                </ul>

            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div id="conteudo" class="content-wrapper">
            @RenderBody()
        </div>


        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 0.0.1
            </div>
            <strong>Copyright &copy; 2019 <a href=" ">Lacerda</a>.</strong> All rights
            reserved.
        </footer>
        <div class="control-sidebar-bg"></div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <!-- ./wrapper -->
    <!-- Bootstrap 3.3.7 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>
    
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
        });
    </script>
</body>
</html>